### ISSUE TITLE
Конфигурационный файл

### ISSUE THREAD

**Issue by EvgenyAK** [EvgenyAK/3db#4]
```yaml
metadata:
    name: 'metadata.yaml'
    recursive: true
load:
    - text
    - binary
load_ignore:
    - *yaml
    - *bin*
```
